version: '3.1'

services:

  ignitedb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres2022
    ports:
      - 15432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080